// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class CategoriaCliente
{
    public int idCategoria { get; set; }

    public string nombreCategoria { get; set; }

    public virtual ICollection<Cliente> Cliente { get; set; } = new List<Cliente>();
}