// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Cliente
{
    public int idCliente { get; set; }

    public string nombre { get; set; }

    public string direccion { get; set; }

    public string telefono { get; set; }

    public string email { get; set; }

    public int? idCategoria { get; set; }

    public int? idZona { get; set; }

    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();

    public virtual CategoriaCliente idCategoriaNavigation { get; set; }

    public virtual Zona idZonaNavigation { get; set; }
}