// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class DetallePedido
{
    public int idDetalle { get; set; }

    public int? idPedido { get; set; }

    public int? idProducto { get; set; }

    public int? cantidad { get; set; }

    public decimal? subtotal { get; set; }

    public virtual Pedido idPedidoNavigation { get; set; }

    public virtual Producto idProductoNavigation { get; set; }
}