// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Entrega
{
    public int idEntrega { get; set; }

    public int? idRuta { get; set; }

    public int? idPedido { get; set; }

    public DateOnly? fechaEntrega { get; set; }

    public string estado { get; set; }

    public virtual Pedido idPedidoNavigation { get; set; }

    public virtual Ruta idRutaNavigation { get; set; }
}