// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Pedido
{
    public int idPedido { get; set; }

    public int? idCliente { get; set; }

    public DateOnly? fecha { get; set; }

    public decimal? total { get; set; }

    public virtual ICollection<DetallePedido> DetallePedido { get; set; } = new List<DetallePedido>();

    public virtual ICollection<Entrega> Entrega { get; set; } = new List<Entrega>();

    public virtual Cliente idClienteNavigation { get; set; }
}