// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class PuntoVenta
{
    public int idPunto { get; set; }

    public string nombrePunto { get; set; }

    public string direccion { get; set; }

    public int? idZona { get; set; }

    public virtual Zona idZonaNavigation { get; set; }
}