// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class Zona
{
    public int idZona { get; set; }

    public string nombreZona { get; set; }

    public virtual ICollection<Cliente> Cliente { get; set; } = new List<Cliente>();

    public virtual ICollection<PuntoVenta> PuntoVenta { get; set; } = new List<PuntoVenta>();

    public virtual ICollection<Ruta> idRuta { get; set; } = new List<Ruta>();
}